// Generated by Selenium IDE
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SuiteTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @org.junit.jupiter.api.Test
    public void verifythattheemergencynoispresentonthehomepage() {
        driver.get("http://www.royalhospitals.com//");
        {
            List<WebElement> elements = driver.findElements(By.id("top-nav-text"));
            assert(elements.size() > 0);
        }
    }
    @org.junit.jupiter.api.Test
    public void navigatetoaboutuspage() {
        driver.get("http://www.royalhospitals.com/");
        driver.manage().window().setSize(new Dimension(1552, 832));
        driver.findElement(By.cssSelector("#menu-item-11873 span")).click();
    }
    @org.junit.jupiter.api.Test
    public void navigatetochannellingpage() {
        driver.get("http://www.royalhospitals.com/");
        driver.manage().window().setSize(new Dimension(1552, 832));
        driver.findElement(By.cssSelector("#menu-item-11872 > a")).click();
        driver.close();
    }
    @org.junit.jupiter.api.Test
    public void navigatetohealthpackagespage() {
        driver.get("http://www.royalhospitals.com/");
        driver.manage().window().setSize(new Dimension(1552, 832));
        driver.findElement(By.cssSelector("#menu-item-11870 span")).click();
    }
    @org.junit.jupiter.api.Test
    public void openthewebsiteinabrowser() {
    }
    @org.junit.jupiter.api.Test
    public void verifythatthemoreaboutushasthecorrectlink() {
        driver.get("http://www.royalhospitals.com/");
        driver.manage().window().setSize(new Dimension(1552, 832));
        driver.findElement(By.linkText("MORE ABOUT US →")).click();
    }
    @org.junit.jupiter.api.Test
    public void verifythatthehomepagelearnmorebuttonworkingcorrect() {
        driver.get("http://www.royalhospitals.com/");
        driver.manage().window().setSize(new Dimension(1552, 832));
        driver.findElement(By.cssSelector("#wpv-expandable-e43196ce8dbcc636f8c7251d6260e763 .btext")).click();
        driver.findElement(By.cssSelector("#menu-item-11874 span")).click();
        driver.findElement(By.cssSelector("#wpv-expandable-ca970f15d66c9a352f3982506cd8c7fc .btext")).click();
        driver.findElement(By.cssSelector("#menu-item-11874 span")).click();
        driver.findElement(By.cssSelector("#wpv-expandable-fd14488e9f698b330deedc95f64ec57b .btext")).click();
        driver.findElement(By.cssSelector("#menu-item-11874 span")).click();
        driver.findElement(By.cssSelector("#wpv-expandable-776c967fe085dd87721c3e39723ee76c .btext")).click();
    }
    @org.junit.jupiter.api.Test
    public void verifythatthecontactusformcansubmit() {
        driver.get("http://www.royalhospitals.com/");
        driver.manage().window().setSize(new Dimension(1552, 832));
        driver.findElement(By.id("menu-item-11868")).click();
        driver.findElement(By.id("menu-item-11868")).click();
        driver.findElement(By.cssSelector("#menu-item-11868 span")).click();
        driver.findElement(By.name("your-name")).click();
        driver.findElement(By.name("your-name")).sendKeys("ameesha");
        driver.findElement(By.name("emal")).click();
        driver.findElement(By.name("emal")).sendKeys("malmiameesha123@gmail.com");
        driver.findElement(By.name("mobile")).click();
        driver.findElement(By.name("mobile")).sendKeys("0704184106");
        driver.findElement(By.name("subject")).click();
        driver.findElement(By.name("subject")).sendKeys("Tesing");
        driver.findElement(By.name("textarea")).click();
        driver.findElement(By.name("textarea")).sendKeys("for testing purpose of university");
        driver.findElement(By.cssSelector("div:nth-child(6) > .wpcf7-form-control")).click();
    }
    @org.junit.jupiter.api.Test
    public void emptycontactformsubmission() {
        driver.get("http://www.royalhospitals.com/");
        driver.manage().window().setSize(new Dimension(1552, 832));
        driver.findElement(By.cssSelector("#menu-item-11868 span")).click();
        driver.findElement(By.cssSelector("div:nth-child(6) > .wpcf7-form-control")).click();
    }
    @Test
    public void invalidcontactformsubmission() {
        driver.get("http://www.royalhospitals.com/");
        driver.manage().window().setSize(new Dimension(1552, 832));
        driver.findElement(By.cssSelector("#menu-item-11868 span")).click();
        driver.findElement(By.cssSelector(".wpcf7-form > div:nth-child(4)")).click();
        driver.findElement(By.name("your-name")).click();
        driver.findElement(By.name("your-name")).sendKeys("ameesha");
        driver.findElement(By.name("emal")).click();
        driver.findElement(By.name("emal")).sendKeys("ameeshagmail.com");
        driver.findElement(By.cssSelector("div:nth-child(6) > .wpcf7-form-control")).click();
    }
}
